import { UserRole } from '../../modules/auth/enums/user-role.enum';
import { Permissions } from './permissions';

export const RolePermissions: Record<UserRole, string[]> = {
  [UserRole.SuperAdmin]: [Permissions.All],
  [UserRole.HRAdmin]: [
    Permissions.DocsRead,
    Permissions.DashboardRead,
    Permissions.CompanyRead,
    Permissions.CompanyCreate,
    Permissions.CompanyUpdate,
    Permissions.CompanyDelete,
    Permissions.EmployeeRead,
    Permissions.EmployeeCreate,
    Permissions.EmployeeUpdate,
    Permissions.DepartmentRead,
    Permissions.DepartmentCreate,
    Permissions.DepartmentUpdate,
    Permissions.DepartmentDelete,
    Permissions.BranchRead,
    Permissions.BranchCreate,
    Permissions.BranchUpdate,
    Permissions.BranchDelete,
    Permissions.WorkScheduleRead,
    Permissions.WorkScheduleCreate,
    Permissions.WorkScheduleUpdate,
    Permissions.WorkScheduleApprove,
    Permissions.HolidayRead,
    Permissions.HolidayCreate,
    Permissions.HolidayUpdate,
    Permissions.AttendanceRead,
    Permissions.AttendanceApprove,
    Permissions.LeaveRead,
    Permissions.LeaveApprove,
    Permissions.LeaveBalanceRead,
    Permissions.LeaveBalanceManage,
    Permissions.PayrollRead,
    Permissions.PayrollCreate,
    Permissions.PayrollUpdate,
    Permissions.WorkflowRead,
    Permissions.NoticeRead,
    Permissions.NotificationRead,
  ],
  [UserRole.Manager]: [
    Permissions.DocsRead,
    Permissions.DashboardRead,
    Permissions.CompanyRead,
    Permissions.EmployeeRead,
    Permissions.DepartmentRead,
    Permissions.BranchRead,
    Permissions.AttendanceRead,
    Permissions.AttendanceApprove,
    Permissions.LeaveRead,
    Permissions.LeaveApprove,
    Permissions.NoticeRead,
    Permissions.NotificationRead,
  ],
  [UserRole.Employee]: [
    Permissions.AttendanceCreate,
    Permissions.AttendanceRead,
    Permissions.LeaveCreate,
    Permissions.LeaveRead,
    Permissions.LeaveBalanceRead,
    Permissions.NoticeRead,
    Permissions.NotificationRead,
  ],
};
